# Site settings
title: Flocktory documentation
email: dev@flocktory.com
description: >
  flocktory.com documentation
  flocktory.com documentation
  flocktory.com documentation
baseurl: ""
url: "http://flocktory.github.io"
twitter_username: flocktory
github_username:  flocktory

# Build settings
markdown: kramdown

collections:
  docs_ru:
    output: true
    permalink: /ru/:path/
  docs_en:
    output: true
    permalink: /en/:path/

# Order of sections in menu
sections_order:
- integration
- general
- exchange
- emails
- precheckout
- push
